on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n easecstandardcontainer -g easecstandardcontainer86d0-rg --location "North Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n easecstandardcontainer --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n easecstandardcontainer --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n easecstandardcontainer --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: easecstandardcontainer.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t easecstandardcontainer.azurecr.io/easecakskluster:${{ github.sha }}
        docker push easecstandardcontainer.azurecr.io/easecakskluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_easecakskluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep easecaksklusterdff9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace easecaksklusterdff9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: easecaksklusterdff9
        container-registry-url: easecstandardcontainer.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: easecaksklusdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: easecaksklusterdff9
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          easecstandardcontainer.azurecr.io/easecakskluster:${{ github.sha }}
        imagepullsecrets: |
          easecaksklusdockerauth